#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1546642624                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1546642624   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Timetable++                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_name_de                               : Stundenplan++                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Timetable App for iPhone and iPad.
app_description_de                        : Stundenplan App für iPhone und iPad.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Fabian Hasse                                
your_link                                 :                     
your_city                                 : Paderborn                                
email_address                             : timetable-app@fabian-hasse.de
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List (EN)                       Edit, add or remove features to be presented.
features                                  :

  - title                                 : Manage timetable
    description                           : Create your own courses, events and examinations to always keep track of your current progress.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : iCal synchronization
    description                           : Import your timetable using an iCal file to automatically synchronize your calendar.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Examination reminders
    description                           : Set reminders for each of your examinations and get notified via push messages (even offline).
    fontawesome_icon_name                 : bell

  - title                                 : Homescreen widgets
    description                           : Use widgets on your homescreen to see your upcoming events and/or exams at a glance.
    fontawesome_icon_name                 : square

  - title                                 : Customization
    description                           : Many customization options like customized course colors, display calendar weeks and more.
    fontawesome_icon_name                 : palette

  - title                                 : iCloud synchronization
    description                           : Automatically synchronize your timetable via iCloud in order to keep it up to date on all your Apple devices.
    fontawesome_icon_name                 : cloud


# Feature List (DE)                       Edit, add or remove features to be presented.
features_de                               :

  - title                                 : Stundenplan verwalten
    description                           : Erstelle eigene Kurse, Veranstaltungen und Prüfungen und behalte so stets den Überblick über deinen derzeitigen Fortschritt.
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : iCal Synchronisierung
    description                           : Importiere deinen Stundenplan mithilfe einer iCal-Datei, um deinen Kalender automatisch zu synchronisieren.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Prüfungs-Erinnerungen
    description                           : Lege dir für jede deiner Prüfungen Erinnerungen an und lasse dich per Push-Notification benachrichtigen (auch offline).
    fontawesome_icon_name                 : bell

  - title                                 : Homescreen Widgets
    description                           : Nutze Widgets auf deinem Homescreen, um anstehende Veranstaltungen und/oder Prüfungen auf einen Blick zu sehen.
    fontawesome_icon_name                 : square

  - title                                 : Personalisierbar
    description                           : Viele Anpassungsmöglichkeiten wie beispielsweise individuelle Kursfarben, Anzeige von Kalenderwochen und mehr.
    fontawesome_icon_name                 : palette

  - title                                 : iCloud Synchronisierung
    description                           : Synchronisiere deinen Stundenplan automatisch über iCloud, um ihn auf all deinen Apple-Geräten immer auf dem neuesten Stand zu halten.
    fontawesome_icon_name                 : cloud



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#2664A2"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#2664A2"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown